name: NSE 09:46 Live Scanner

on:
  schedule:
    # 04:16 UTC = 09:46 IST
    # Monday-Friday
    - cron: "16 4 * * 1-5"

  workflow_dispatch:

permissions:
  contents: read

jobs:

  live-market-scan:

    runs-on: ubuntu-latest

    timeout-minutes: 15

    env:
      TZ: Asia/Kolkata

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run single 09:46 IST live scan
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI1U0NRTEMiLCJqdGkiOiI2YWIxOTQyYzExMDA2ZDE4Nzk5NzVlNjYiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaXNFeHRlbmRlZCI6dHJ1ZSwiaWF0IjoxNzkwMDIyNzAwLCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE4MjE1NjQwMDB9.hZWxTPTvOA5c_mpXk95aXNovdRq5gXQvDwEMzM3EUdk}}
          TELEGRAM_CHAT_ID: ${{ secrets.1860594381}}
          MIN_TURNOVER_CR: "2.0"
          TOP_SHORTS_TO_SHOW: "5"
          TOP_LONGS_TO_SHOW: "3"
        run: |
          python runner.py
