name: NSE Momentum Daily Bot

on:
  schedule:
    # 9:31 AM IST is 04:01 AM UTC, Monday-Friday
    - cron: '1 4 * * 1-5'
  workflow_dispatch:

jobs:
  execute-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Telegram Bot Runner
        env:
          TELEGRAM_BOT_TOKEN: "8984037851:AAGnc5Tm088pqdilp8kL-I5giUXylP8hRQQ"
          TELEGRAM_CHAT_ID: "1860594381"
        run: python runner.py
